### ISSUE TITLE
Student shouldn't be able to fill registration info without registration in WebOodi

### ISSUE THREAD

**Issue by maarila** [labtool/labtool#303] opened 2018-06-04 11:35 UTC
Currently a user who is not registered to a course gets an error message saying no registration in WebOodi after filling in project name and project url, but the check should already happen when clicking Register button.

**Comment by ValheKouneli** [comment] 2018-06-04 21:25
I accidentally made a duplicate of this, but the duplicate is maybe a bit more elaborate, so closing this one.

**Closed by ValheKouneli** 2018-06-04 21:25 UTC
Labels: duplicate, frontend
